version: '3'
services:
  mongodb-reach:
    image: mongo:latest
    container_name: mongodb-reach
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: main_db
    volumes:
      - mongodb-reach:/data/db
    ports:
      - '27017:27017'

  api:
    build:
      context: ./api
    container_name: reach-api
    working_dir: /code/app
    volumes:
      - ./api:/code/app
    environment:
      MONGODB_URL: mongodb://admin:admin@mongodb-reach:27017
    ports:
      - '8000:8000'
    restart: on-failure

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    container_name: web-ui
    stdin_open: true
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules

volumes:
  mongodb-reach:

